# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:03:02+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class GoogleCloudBillingBudgetsV1beta1AllUpdatesRule(BaseModel):
    disableDefaultIamRecipients: Optional[bool] = Field(
        None,
        description='Optional. When set to true, disables default notifications sent when a threshold is exceeded. Default notifications are sent to those with Billing Account Administrator and Billing Account User IAM roles for the target account.',
    )
    monitoringNotificationChannels: Optional[List[str]] = Field(
        None,
        description='Optional. Targets to send notifications to when a threshold is exceeded. This is in addition to default recipients who have billing account IAM roles. The value is the full REST resource name of a monitoring notification channel with the form `projects/{project_id}/notificationChannels/{channel_id}`. A maximum of 5 channels are allowed. See https://cloud.google.com/billing/docs/how-to/budgets-notification-recipients for more details.',
    )
    pubsubTopic: Optional[str] = Field(
        None,
        description="Optional. The name of the Pub/Sub topic where budget related messages will be published, in the form `projects/{project_id}/topics/{topic_id}`. Updates are sent at regular intervals to the topic. The topic needs to be created before the budget is created; see https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications for more details. Caller is expected to have `pubsub.topics.setIamPolicy` permission on the topic when it's set for a budget, otherwise, the API call will fail with PERMISSION_DENIED. See https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications#permissions_required_for_this_task for more details on Pub/Sub roles and permissions.",
    )
    schemaVersion: Optional[str] = Field(
        None,
        description='Optional. Required when AllUpdatesRule.pubsub_topic is set. The schema version of the notification sent to AllUpdatesRule.pubsub_topic. Only "1.0" is accepted. It represents the JSON schema as defined in https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications#notification_format.',
    )


class CalendarPeriod(Enum):
    CALENDAR_PERIOD_UNSPECIFIED = 'CALENDAR_PERIOD_UNSPECIFIED'
    MONTH = 'MONTH'
    QUARTER = 'QUARTER'
    YEAR = 'YEAR'


class CreditTypesTreatment(Enum):
    CREDIT_TYPES_TREATMENT_UNSPECIFIED = 'CREDIT_TYPES_TREATMENT_UNSPECIFIED'
    INCLUDE_ALL_CREDITS = 'INCLUDE_ALL_CREDITS'
    EXCLUDE_ALL_CREDITS = 'EXCLUDE_ALL_CREDITS'
    INCLUDE_SPECIFIED_CREDITS = 'INCLUDE_SPECIFIED_CREDITS'


class GoogleCloudBillingBudgetsV1beta1LastPeriodAmount(BaseModel):
    pass


class SpendBasis(Enum):
    BASIS_UNSPECIFIED = 'BASIS_UNSPECIFIED'
    CURRENT_SPEND = 'CURRENT_SPEND'
    FORECASTED_SPEND = 'FORECASTED_SPEND'


class GoogleCloudBillingBudgetsV1beta1ThresholdRule(BaseModel):
    spendBasis: Optional[SpendBasis] = Field(
        None,
        description='Optional. The type of basis used to determine if spend has passed the threshold. Behavior defaults to CURRENT_SPEND if not set.',
    )
    thresholdPercent: Optional[float] = Field(
        None,
        description='Required. Send an alert when this threshold is exceeded. This is a 1.0-based percentage, so 0.5 = 50%. Validation: non-negative number.',
    )


class GoogleProtobufEmpty(BaseModel):
    pass


class GoogleTypeDate(BaseModel):
    day: Optional[int] = Field(
        None,
        description="Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
    )
    month: Optional[int] = Field(
        None,
        description='Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.',
    )
    year: Optional[int] = Field(
        None,
        description='Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.',
    )


class GoogleTypeMoney(BaseModel):
    currencyCode: Optional[str] = Field(
        None, description='The three-letter currency code defined in ISO 4217.'
    )
    nanos: Optional[int] = Field(
        None,
        description='Number of nano (10^-9) units of the amount. The value must be between -999,999,999 and +999,999,999 inclusive. If `units` is positive, `nanos` must be positive or zero. If `units` is zero, `nanos` can be positive, zero, or negative. If `units` is negative, `nanos` must be negative or zero. For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000.',
    )
    units: Optional[str] = Field(
        None,
        description='The whole units of the amount. For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleCloudBillingBudgetsV1beta1BudgetAmount(BaseModel):
    lastPeriodAmount: Optional[GoogleCloudBillingBudgetsV1beta1LastPeriodAmount] = (
        Field(
            None,
            description="Use the last period's actual spend as the budget for the present period. LastPeriodAmount can only be set when the budget's time period is a Filter.calendar_period. It cannot be set in combination with Filter.custom_period.",
        )
    )
    specifiedAmount: Optional[GoogleTypeMoney] = Field(
        None,
        description='A specified amount to use as the budget. `currency_code` is optional. If specified when creating a budget, it must match the currency of the billing account. If specified when updating a budget, it must match the currency_code of the existing budget. The `currency_code` is provided on output.',
    )


class GoogleCloudBillingBudgetsV1beta1CustomPeriod(BaseModel):
    endDate: Optional[GoogleTypeDate] = Field(
        None,
        description="Optional. The end date of the time period. Budgets with elapsed end date won't be processed. If unset, specifies to track all usage incurred since the start_date.",
    )
    startDate: Optional[GoogleTypeDate] = Field(
        None, description='Required. The start date must be after January 1, 2017.'
    )


class GoogleCloudBillingBudgetsV1beta1Filter(BaseModel):
    calendarPeriod: Optional[CalendarPeriod] = Field(
        None,
        description='Optional. Specifies to track usage for recurring calendar period. For example, assume that CalendarPeriod.QUARTER is set. The budget will track usage from April 1 to June 30, when the current calendar month is April, May, June. After that, it will track usage from July 1 to September 30 when the current calendar month is July, August, September, so on.',
    )
    creditTypes: Optional[List[str]] = Field(
        None,
        description='Optional. If Filter.credit_types_treatment is INCLUDE_SPECIFIED_CREDITS, this is a list of credit types to be subtracted from gross cost to determine the spend for threshold calculations. See [a list of acceptable credit type values](https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables#credits-type). If Filter.credit_types_treatment is **not** INCLUDE_SPECIFIED_CREDITS, this field must be empty.',
    )
    creditTypesTreatment: Optional[CreditTypesTreatment] = Field(
        None,
        description='Optional. If not set, default behavior is `INCLUDE_ALL_CREDITS`.',
    )
    customPeriod: Optional[GoogleCloudBillingBudgetsV1beta1CustomPeriod] = Field(
        None,
        description='Optional. Specifies to track usage from any start date (required) to any end date (optional). This time period is static, it does not recur.',
    )
    labels: Optional[Dict[str, List]] = Field(
        None,
        description='Optional. A single label and value pair specifying that usage from only this set of labeled resources should be included in the budget. If omitted, the report will include all labeled and unlabeled usage. An object containing a single `"key": value` pair. Example: `{ "name": "wrench" }`. _Currently, multiple entries or multiple values per entry are not allowed._',
    )
    projects: Optional[List[str]] = Field(
        None,
        description='Optional. A set of projects of the form `projects/{project}`, specifying that usage from only this set of projects should be included in the budget. If omitted, the report will include all usage for the billing account, regardless of which project the usage occurred on.',
    )
    services: Optional[List[str]] = Field(
        None,
        description='Optional. A set of services of the form `services/{service_id}`, specifying that usage from only this set of services should be included in the budget. If omitted, the report will include usage for all the services. The service names are available through the Catalog API: https://cloud.google.com/billing/v1/how-tos/catalog-api.',
    )
    subaccounts: Optional[List[str]] = Field(
        None,
        description='Optional. A set of subaccounts of the form `billingAccounts/{account_id}`, specifying that usage from only this set of subaccounts should be included in the budget. If a subaccount is set to the name of the parent account, usage from the parent account will be included. If omitted, the report will include usage from the parent account and all subaccounts, if they exist.',
    )


class GoogleCloudBillingBudgetsV1beta1Budget(BaseModel):
    allUpdatesRule: Optional[GoogleCloudBillingBudgetsV1beta1AllUpdatesRule] = Field(
        None,
        description='Optional. Rules to apply to notifications sent based on budget spend and thresholds.',
    )
    amount: Optional[GoogleCloudBillingBudgetsV1beta1BudgetAmount] = Field(
        None, description='Required. Budgeted amount.'
    )
    budgetFilter: Optional[GoogleCloudBillingBudgetsV1beta1Filter] = Field(
        None,
        description="Optional. Filters that define which resources are used to compute the actual spend against the budget amount, such as projects, services, and the budget's time period, as well as other filters.",
    )
    displayName: Optional[str] = Field(
        None, description='User data for display name in UI. Validation: <= 60 chars.'
    )
    etag: Optional[str] = Field(
        None,
        description='Optional. Etag to validate that the object is unchanged for a read-modify-write operation. An empty etag will cause an update to overwrite other changes.',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name of the budget. The resource name implies the scope of a budget. Values are of the form `billingAccounts/{billingAccountId}/budgets/{budgetId}`.',
    )
    thresholdRules: Optional[List[GoogleCloudBillingBudgetsV1beta1ThresholdRule]] = (
        Field(
            None,
            description='Optional. Rules that trigger alerts (notifications of thresholds being crossed) when spend exceeds the specified percentages of the budget. Optional for `pubsubTopic` notifications. Required if using email notifications.',
        )
    )


class GoogleCloudBillingBudgetsV1beta1CreateBudgetRequest(BaseModel):
    budget: Optional[GoogleCloudBillingBudgetsV1beta1Budget] = Field(
        None, description='Required. Budget to create.'
    )


class GoogleCloudBillingBudgetsV1beta1ListBudgetsResponse(BaseModel):
    budgets: Optional[List[GoogleCloudBillingBudgetsV1beta1Budget]] = Field(
        None, description='List of the budgets owned by the requested billing account.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='If not empty, indicates that there may be more budgets that match the request; this value should be passed in a new `ListBudgetsRequest`.',
    )


class GoogleCloudBillingBudgetsV1beta1UpdateBudgetRequest(BaseModel):
    budget: Optional[GoogleCloudBillingBudgetsV1beta1Budget] = Field(
        None,
        description='Required. The updated budget object. The budget to update is specified by the budget name in the budget.',
    )
    updateMask: Optional[str] = Field(
        None,
        description='Optional. Indicates which fields in the provided budget to update. Read-only fields (such as `name`) cannot be changed. If this is not provided, then only fields with non-default values from the request are updated. See https://developers.google.com/protocol-buffers/docs/proto3#default for more details about default values.',
    )
